import { pastEntries } from "./game.js";
import { arrayRandomExclude } from "./utils.js";
import type { CountryCode } from "./types.js";

const { FLAG_IMAGE_REPO_PREFIX, FLAG_IMAGE_REPO_SUFFIX } = process.env;

const countries = {
  "AD": ["Andorra"],
  "AE": ["United Arab Emirates", "UAE"],
  "AF": ["Afghanistan"],
  "AG": ["Antigua and Barbuda"],
  "AI": ["Anguilla"],
  "AL": ["Albania"],
  "AM": ["Armenia"],
  "AO": ["Angola"],
  "AQ": ["Antarctica"],
  "AR": ["Argentina"],
  "AS": ["American Samoa", "Samoa"],
  "AT": ["Austria"],
  "AU": ["Australia"],
  "AW": ["Aruba"],
  "AX": ["Aland Islands"],
  "AZ": ["Azerbaijan"],
  "BA": ["Bosnia"],
  "BB": ["Barbados"],
  "BD": ["Bangladesh"],
  "BE": ["Belgium"],
  "BF": ["Burkina Faso"],
  "BG": ["Bulgaria"],
  "BH": ["Bahrain"],
  "BI": ["Burundi"],
  "BJ": ["Benin"],
  "BM": ["Bermuda"],
  "BN": ["Brunei Darussalam", "Brunei"],
  "BO": ["Bolivia"],
  "BR": ["Brazil"],
  "BS": ["Bahamas"],
  "BT": ["Bhutan"],
  "BW": ["Botswana"],
  "BY": ["Belarus"],
  "BZ": ["Belize"],
  "CA": ["Canada"],
  "CC": ["Cocos Islands"],
  "CD": ["The Democratic Republic of the Congo", "DRC", "DR Congo"],
  "CF": ["Central African Republic", "CAR"],
  "CG": ["Republic of the Congo", "ROC", "Congo"],
  "CH": ["Switzerland"],
  "CI": ["Cote d'Ivoire"],
  "CK": ["Cook Islands"],
  "CL": ["Chile"],
  "CM": ["Cameroon"],
  "CN": ["China"],
  "CO": ["Colombia"],
  "CR": ["Costa Rica"],
  "CU": ["Cuba"],
  "CV": ["Cape Verde"],
  "CW": ["Curacao"],
  "CX": ["Christmas Island"],
  "CY": ["Cyprus"],
  "CZ": ["Czech Republic"],
  "DE": ["Germany"],
  "DJ": ["Djibouti"],
  "DK": ["Denmark"],
  "DM": ["Dominica"],
  "DO": ["Dominican Republic", "Dominican"],
  "DZ": ["Algeria"],
  "EC": ["Ecuador"],
  "EE": ["Estonia"],
  "EG": ["Egypt"],
  "EH": ["Western Sahara"],
  "ER": ["Eritrea"],
  "ES": ["Spain"],
  "ET": ["Ethiopia"],
  "EU": ["European Union"],
  "FI": ["Finland"],
  "FJ": ["Fiji"],
  "FK": ["Falkland Islands", "Falklands"],
  "FM": ["Micronesia"],
  "FO": ["Faroe Islands"],
  "FR": ["France"],
  "GA": ["Gabon"],
  "GB-ENG": ["England"],
  "GB-SCT": ["Scotland"],
  "GB-WLS": ["Wales"],
  "GB": ["United Kingdom", "UK"],
  "GD": ["Grenada"],
  "GE": ["Georgia"],
  "GG": ["Guernsey"],
  "GH": ["Ghana"],
  "GI": ["Gibraltar"],
  "GL": ["Greenland"],
  "GM": ["Gambia"],
  "GN": ["Guinea"],
  "GQ": ["Equatorial Guinea"],
  "GR": ["Greece"],
  "GS": ["South Georgia"],
  "GT": ["Guatemala"],
  "GU": ["Guam"],
  "GW": ["Guinea-Bissau"],
  "GY": ["Guyana"],
  "HK": ["Hong Kong"],
  "HN": ["Honduras"],
  "HR": ["Croatia"],
  "HT": ["Haiti"],
  "HU": ["Hungary"],
  "ID": ["Indonesia"],
  "IE": ["Ireland"],
  "IL": ["Israel"],
  "IM": ["Isle of Man"],
  "IN": ["India"],
  "IQ": ["Iraq"],
  "IR": ["Iran"],
  "IS": ["Iceland"],
  "IT": ["Italy"],
  "JE": ["Jersey"],
  "JM": ["Jamaica"],
  "JO": ["Jordan"],
  "JP": ["Japan"],
  "KE": ["Kenya"],
  "KG": ["Kyrgyzstan"],
  "KH": ["Cambodia"],
  "KI": ["Kiribati"],
  "KM": ["Comoros"],
  "KN": ["Saint Kitts"],
  "KP": ["North Korea"],
  "KR": ["South Korea"],
  "KW": ["Kuwait"],
  "KY": ["Cayman Islands"],
  "KZ": ["Kazakhstan"],
  "LA": ["Laos"],
  "LB": ["Lebanon"],
  "LC": ["Saint Lucia"],
  "LI": ["Liechtenstein"],
  "LK": ["Sri Lanka"],
  "LR": ["Liberia"],
  "LS": ["Lesotho"],
  "LT": ["Lithuania"],
  "LU": ["Luxembourg"],
  "LV": ["Latvia"],
  "LY": ["Libya"],
  "MA": ["Morocco"],
  "MC": ["Monaco"],
  "MD": ["Moldova"],
  "ME": ["Montenegro"],
  "MG": ["Madagascar"],
  "MH": ["Marshall Islands", "Marshall"],
  "MK": ["North Macedonia"],
  "ML": ["Mali"],
  "MM": ["Myanmar"],
  "MN": ["Mongolia"],
  "MO": ["Macao"],
  "MR": ["Mauritania"],
  "MS": ["Montserrat"],
  "MT": ["Malta"],
  "MU": ["Mauritius"],
  "MV": ["Maldives"],
  "MW": ["Malawi"],
  "MX": ["Mexico"],
  "MY": ["Malaysia"],
  "MZ": ["Mozambique"],
  "NA": ["Namibia"],
  "NE": ["Niger"],
  "NF": ["Norfolk Island"],
  "NG": ["Nigeria"],
  "NI": ["Nicaragua"],
  "NL": ["Netherlands"],
  "NO": ["Norway"],
  "NP": ["Nepal"],
  "NR": ["Nauru"],
  "NU": ["Niue"],
  "NZ": ["New Zealand"],
  "OM": ["Oman"],
  "PA": ["Panama"],
  "PE": ["Peru"],
  "PF": ["French Polynesia"],
  "PG": ["Papua New Guinea"],
  "PH": ["Philippines"],
  "PK": ["Pakistan"],
  "PL": ["Poland"],
  "PN": ["Pitcairn"],
  "PR": ["Puerto Rico"],
  "PS": ["Palestine"],
  "PT": ["Portugal"],
  "PW": ["Palau"],
  "PY": ["Paraguay"],
  "QA": ["Qatar"],
  "RO": ["Romania"],
  "RS": ["Serbia"],
  "RU": ["Russia"],
  "RW": ["Rwanda"],
  "SA": ["Saudi Arabia", "Saudi"],
  "SB": ["Solomon Islands", "Solomon"],
  "SC": ["Seychelles"],
  "SD": ["Sudan"],
  "SE": ["Sweden"],
  "SG": ["Singapore"],
  "SI": ["Slovenia"],
  "SK": ["Slovakia"],
  "SL": ["Sierra Leone"],
  "SM": ["San Marino"],
  "SN": ["Senegal"],
  "SO": ["Somalia"],
  "SR": ["Suriname"],
  "SS": ["South Sudan"],
  "ST": ["Sao Tome and Principe", "Sao Tome"],
  "SV": ["El Salvador"],
  "SX": ["Sint Maarten"],
  "SY": ["Syria"],
  "SZ": ["Swaziland"],
  "TD": ["Chad"],
  "TG": ["Togo"],
  "TH": ["Thailand"],
  "TJ": ["Tajikistan"],
  "TK": ["Tokelau"],
  "TL": ["Timor-Leste"],
  "TM": ["Turkmenistan"],
  "TN": ["Tunisia"],
  "TO": ["Tonga"],
  "TR": ["Turkey"],
  "TT": ["Trinidad and Tobago"],
  "TV": ["Tuvalu"],
  "TW": ["Taiwan"],
  "TZ": ["Tanzania"],
  "UA": ["Ukraine"],
  "UG": ["Uganda"],
  "US": ["United States of America", "United States", "USA"],
  "UY": ["Uruguay"],
  "UZ": ["Uzbekistan"],
  "VC": ["Saint Vincent"],
  "VE": ["Venezuela"],
  "VG": ["Virgin Islands"],
  "VI": ["Virgin Islands"],
  "VN": ["Vietnam"],
  "VU": ["Vanuatu"],
  "WS": ["Samoa"],
  "XK": ["Kosovo"],
  "YE": ["Yemen"],
  "ZA": ["South Africa"],
  "ZM": ["Zambia"],
  "ZW": ["Zimbabwe"]
} as const;

const countryCodes = Object.keys(countries) as CountryCode[];

const codeToImage = (code: CountryCode) => `${FLAG_IMAGE_REPO_PREFIX}${code.toLowerCase()}${FLAG_IMAGE_REPO_SUFFIX}`;

const randomCountryCode = () => arrayRandomExclude(countryCodes, pastEntries) as CountryCode;

export default countries;
export { countryCodes, codeToImage, randomCountryCode };
